version: '3.4'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Aa123456789!
    networks:
      - catalog_net

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - catalog_net

volumes:
  catalog_data:

networks:
  catalog_net: